DB_NAME = "m3m3"
DB_USER = "root"
DB_PASS = "mypass"
DB_RESET = "yes"
EMAIL = "m3m3@m3m3.com"
EMAIL_PASS = "mypass"
SMTP = "mail.mail.com"
SMTP_PORT = "587"
ADMIN_PASS = "mypass"
HTTP_DIR = "/var/www/m3m3/"
SERVER_HOST = "http://myip"
SERVER_PORT = "8080"